### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by MerRM** [jngo102/Butterfly#4]
### Describe the problem

A button that shows the ReadMe of the mod when clicked (If it has)
Only appears when clicking at the description.

### Describe the feature that you'd like

![Captura (1)](https://user-images.githubusercontent.com/103300922/164126600-272a77b3-b90e-47bb-bab2-e116fdd3c89e.png)

**Comment by jngo102** [comment]
Please check out the [latest release](https://github.com/jngo102/Butterfly/releases/tag/20.04.2022) to verify that this feature has been implemented correctly.

**Comment by MerRM** [comment]
> Please check out the [latest release](https://github.com/jngo102/Butterfly/releases/tag/20.04.2022) to verify that this feature has been implemented correctly.

It works perfectly and exactly how I imagined, this will help so much at the moment of looking through new mods released.
Great Job! 🎉

**Comment by jngo102** [comment]
In that case, I will close this issue now.
