### ISSUE TITLE
[Feature] Automatically close/kill hollow knight

### ISSUE THREAD

**Issue by SFGrenade** [jngo102/Butterfly#5]
### Describe the problem

Installing the api while hollow knight is running does not work.

### Describe the feature that you'd like

When un-/installing the api or dis-/enabling or un-/installing mods, it can check if hollow knight is running, and if it is, a popup can open that asks if butterfly should close it.

### Alternatives considered

Don't let the user do the operation when hollow knight is running.

**Comment by jngo102** [comment]
The feature has been added in [c88206893ecb337ea14f93846306ce1a8cdda487](https://github.com/jngo102/Butterfly/commit/c88206893ecb337ea14f93846306ce1a8cdda487). Check out the latest release to see if the feature is working; I don't know of any aliases for the game executable other than "hollow_knight" and "Hollow Knight".
