### ISSUE TITLE
Tauri build error

### ISSUE THREAD

**Issue by Dastan21** [jngo102/Butterfly#9]
Hi, I tried to build the project on my computer (Windows 10) and I get this error when building it with tauri :

![tauri_build_error](https://user-images.githubusercontent.com/58090137/174784023-19f71304-3668-4868-a6bb-a65d53092d80.png)

`yarn build` works fine tho

![image](https://user-images.githubusercontent.com/58090137/174784369-4088222e-2392-4fdf-bb4f-f9557b0f98bd.png)

Idk if you can help, I've already searched for solutions but I found nothing...

Here is the output of `yarn tauri info`:

![image](https://user-images.githubusercontent.com/58090137/174784729-486e3555-7cf2-4c4c-b1a2-15f5217e5e31.png)

**Comment by jngo102** [comment]
Have you installed Rust through the [rustup installer](https://rustup.rs/)?

**Comment by Dastan21** [comment]
Indeed that's what was missing, thanks. You should add a note to the **Building from Source** section.
